location          = "westeurope"
location_short    = "euw"
subscription_spec = "neu"
certificate_name  = "dtcloudapps-com"
app_fqdn          = "hello-world-test-app.redbeach-cc61033c.westeurope.azurecontainerapps.io"
host_name         = "app-one-new-test.dtcloudapps.com"
